weekend/card/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Date  : 2018-03-24
# Author: juzi
# E-mail: jentlewoo@gmail.com


from django.urls import path

from . import views

app_name = 'card'
urlpatterns = [
    path('', views.index, name='index'),
    path('inputpage/', views.inputpage, name='inputpage'),
    path('make/', views.make, name='make'),
    ]

weekend/polls/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Date  : 2018-03-16
# Author: juzi
# E-mail: jentlewoo@gmail.com

from django.urls import path

from . import views


app_name = 'polls'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

weekend/weekend/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('card/', include('card.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

weekend/card/models.py
from django.db import models

# Create your models here.

weekend/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

weekend/card/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from . import pilscript

# Create your views here.

def index(request):
    return render(request, 'card/index.html')


    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    # context = {
    #     'latest_question_list': latest_question_list,
    # }
    # return HttpResponse(template.render(context, request))

def inputpage(request):
    return render(request, 'card/inputpage.html')

def make(request):
    ret = pilscript.add_text()
    username = request.POST['username']
    return render(request, 'card/make.html', {'username': username,'ret': ret})

weekend/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """返回最后5个问题 / 不包括未来时间段的"""
        return Question.objects.filter(
                pub_date__lte = timezone.now()
                ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

weekend/card/templates/card/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1">
    <title>嘿，你的嘉宾证</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'card/style.css' %}" />
  </head>
  <body>
    <div class='container'>
      <p class="cook-say">嘿，伙计，来领你的嘉宾证。</p>
      <div class="footer">
        <p>
          <a href="{% url 'card:inputpage' %}" class="make-button">
            领 取
          </a>
        </p>
      </div>
    </div>
  </body>
</html>

weekend/card/templates/card/inputpage.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1">
    <title>嘿，你的嘉宾证</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'card/style.css' %}" />
  </head>
  <body>
    <div class="make-ctn">
      <p class="cook-say">请在下方输入你的名字<br>将印刻到你的嘉宾证中
      </p>
      <form action="{% url 'card:make' %}" method="post">
        {% csrf_token %}
        <p><input type='text' name='username' placeholder='例如：Larry Page' required></p>
        <p><input type='submit' class="make-button" value="生成"></p>
      </form>
    </div>
  </body>
</html>

weekend/card/templates/card/make.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1">
    <title>嘿，你的嘉宾证</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'card/style.css' %}" />
  </head>
  <body>


<div class="container">


    <img src='../../static/card/images/123.png' style="width:100%">
  </div>
    <!-- <p>
      <img src="{{ ret }}"/>
    </p> -->
  </body>
</html>

weekend/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
  <p>
    <strong>{{ error_message }}</strong>
  </P>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
  <input type="submit" value="Vote" />
</form>

weekend/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

weekend/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>